title: Hadia Hameed
description: Computer Science Geek
permalink: /blog/:year/:month/:day/:title
collections:
  projects:
    output: true
show_downloads: false
google_analytics: UA-146885821-1
social_links:
  linkedin: https://www.linkedin.com/in/hadia-hameed/
  gmail: mailto:hadiahameeduet@gmail.com
  github: http://github.com/hadiahameed
  tableau: https://public.tableau.com/app/profile/hadia.hameed6932
theme: jekyll-theme-cayman
