title: Hadia Hameed
description: Computer Science Geek
permalink: /blog/:year/:month/:day/:title
show_downloads: false
google_analytics: UA-146885821-1
social_links:
  linkedin: https://www.linkedin.com/in/hadia-hameed/
  gmail: mailto:hadiahameeduet@gmail.com
  github: http://github.com/hadiahameed
theme: jekyll-theme-cayman

#Source: https://github.com/Haacked/haacked.com/pull/316/commits/881fa955e08dd988fd34c60537084016359a7e58
emptyArray: []

comments:
  receiver: https://haacked-blog.azurewebsites.net/api/PostComment

authors:
  haacked:
    name: haacked
    email: haacked@gmail.com
    url: https://haacked.com

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: damieng
      commenting: open
  -
    scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: damieng
      commenting: open
