title: Hadia Hameed
description: Computer Science Geek
permalink: /blog/:year/:month/:day/:title
show_downloads: false
google_analytics: UA-146885821-1
social_links:
  linkedin: https://www.linkedin.com/in/hadia-hameed/
  gmail: mailto:hadiahameeduet@gmail.com
  github: http://github.com/hadiahameed
theme: jekyll-theme-cayman
