title: Hadia Hameed
description:
permalink: /blog/:year/:month/:day/:title
show_downloads: false
google_analytics: UA-146885821-1
github:
  zip_url: https://github.com/hadiahameed
theme: jekyll-theme-cayman
